from setuptools import find_packages
from setuptools import setup

setup(name='tennis_model',
      version='0.1.6',
      description='Framework for sport modelling',
      url='http://github.com/danielhp95/Tennis_model',
      author='Daniel Hernandez',
      author_email='danielhp95@gmail.com',
      license='MIT',
      include_package_data=True,
      packages=find_packages(include=['tennis_model','tennis_model.*']),
      install_requires=[
        'appdirs==1.4.3',
        'coverage==4.3.4',
        'cycler==0.10.0',
        'decorator==4.0.6',
        'et-xmlfile==1.0.1',
        'functools32==3.2.3.post2',
        'ipython==2.4.1',
        'jdcal==1.3',
        'matplotlib==2.0.0',
        'nose==1.3.7',
        'numpy==1.12.1',
        'openpyxl==2.4.7',
        'packaging==16.8',
        'pandas==0.19.2',
        'pexpect==4.0.1',
        'pip==9.0.1',
        'ptyprocess==0.5',
        'py==1.4.33',
        'pycrypto==2.6.1',
        'pyparsing==2.2.0',
        'pytest==3.0.7',
        'pytest-cov==2.4.0',
        'python-dateutil==2.6.0',
        'pytz==2017.2',
        'setuptools==35.0.2',
        'simplegeneric==0.8.1',
        'six==1.10.0',
        'subprocess32==3.2.7',
        'wheel==0.29.0',
        'xlrd==1.0.0',
        'xlwt==1.2.0',
      ],
      zip_safe=False)
